#!/bin/bash

function publish () {
  yarn publish --cwd $1 --registry http://localhost:4000 --non-interactive
}

# start_verdaccio
yarn verdaccio --listen 4000 --config ./verdaccio.yaml &
VERDACCIO_PID=$!
# wait for verdaccio layer to start
while ! curl --output /dev/null --silent --head --fail http://localhost:4000
do 
  sleep 1 && echo -n .
done

# iterate over workspace packages to publish
for PACKAGE in $(find ~+/packages -mindepth 1 -maxdepth 1 -type d)
do
  PACKAGE_NAME=$(jq '.name' -r $PACKAGE/package.json)
  PACKAGE_VERSION=$(jq '.version' -r $PACKAGE/package.json)

  echo "Publishing $PACKAGE_NAME@$PACKAGE_VERSION"
  # publish workspace package to verdaccio
  publish $PACKAGE
done

# push resources (should install lambda deps from verdaccio)
echo "Running amplify push..."
amplify push -y

# kill verdaccio, remove storage
echo "Killing Verdaccio and removing storage..."
kill $VERDACCIO_PID && rm -rf .verdaccio;
echo "Success! 🙌"